apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-support-rag-chatbot-data
  labels:
    app.kubernetes.io/name: document-support-rag-chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
