apiVersion: v1
kind: Service
metadata:
  name: document-support-rag-chatbot
  labels:
    app.kubernetes.io/name: document-support-rag-chatbot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: document-support-rag-chatbot
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
